engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
  - tests/
  - flask_swag/resources/
  - docs/
  - README.rst
  - tox.ini
  - MANIFEST.in
  - LICENSE.txt
