language: python
python: 3.5
env:
 - TOX_ENV=py34
 - TOX_ENV=py35
 - TOX_ENV=docs
install:
 - pip install tox
script:
 - tox -e $TOX_ENV
before_install:
  - pip install codecov
after_success:
  - codecov
